server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route
            # 路由的id,没有规定规则但要求唯一,建议配合服务名
            #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
              - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            #- After=2021-04-27T22:28:11.338+08:00[Asia/Shanghai] 超过这个时间才可以访问
            #- Coolie=username,zzyy 只有带着Coolie才可以访问成功
            #- Header=X-Requesat-Id, \d+ #必须带有请求头且要有X-Requesat-Id属性并且值为正整数的正则表达式
      discovery:
        locator:
          enabled: true


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/